### ISSUE TITLE
Error on backend return small msg.

### ISSUE THREAD

**Issue by KKKIIO** [wgtdkp/julia#9]
The function `handle_upstream` didn't handle the small msg correctly:
```c
int handle_upstream(connection_t* uc) {
    request_t* r = uc->r;
    buffer_t* b = &r->sb;
    int err = buffer_recv(b, uc->fd);
    if (err == OK) {
        // The connection has been closed by peer
        return ERROR; // didn't connection_enable_out(r->c) when first called the err is ok !!!
    } else if (err == ERROR) {
        // Error in backend
        response_build_err(r, 503);
        return ERROR;
    } else if (buffer_full(b)) {
        //connection_disable_in(uc);
    }
    connection_enable_out(r->c);
    return err;
}
```
test code:
```python
# server side
from flask import Flask
app = Flask(__name__)

@app.route('/small')
def test_small():
    return "small message"
```

**Comment by wgtdkp** [comment]
oops, it should call _connection\_enable\_out(r->c)_ after _buffer\_recv()_ immediately.
[commit](https://github.com/wgtdkp/julia/commit/502b9cba2d1c70f4903f986ae775917f6f6731b1) for this.
It should also be an error for big response from backend, but it just works fine...
I didn't do test as I would have no access to computer soon. If your find bugs later, it will be great if you could give me a pull request. Thanks very much for this days.

**Comment by wgtdkp** [comment]
The comment is misleading.
As the second request could be in the same recv buffer with first request. There is no easy way to forbid pipelining.
